# Generated by Django 4.0 on 2022-09-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='units_of_measure',
            new_name='measurement_unit',
        ),
    ]
